# Generated by Django 5.0.9 on 2026-07-15 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, upload_to='podcast/thumbnails/')),
                ('banner', models.ImageField(blank=True, upload_to='podcast/banners/')),
                ('author_name', models.CharField(default='Redaksi', max_length=200)),
                ('category', models.CharField(choices=[('NEWS', 'Berita'), ('ENTERTAINMENT', 'Hiburan'), ('EDUCATION', 'Pendidikan'), ('TECHNOLOGY', 'Teknologi'), ('MUSIC', 'Musik'), ('RELIGION', 'Agama'), ('TALK_SHOW', 'Talk Show'), ('SPORTS', 'Olahraga'), ('BUSINESS', 'Bisnis'), ('CULTURE', 'Budaya'), ('HEALTH', 'Kesehatan'), ('OTHER', 'Lainnya')], default='OTHER', max_length=20)),
                ('language', models.CharField(default='id', max_length=10)),
                ('episode_count', models.PositiveIntegerField(default=0)),
                ('itunes_url', models.URLField(blank=True, default='')),
                ('spotify_url', models.URLField(blank=True, default='')),
                ('google_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350)),
                ('description', models.TextField(blank=True, default='')),
                ('audio_file', models.FileField(upload_to='podcast/episodes/audio/')),
                ('audio_url', models.URLField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, upload_to='podcast/episodes/covers/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('episode_number', models.PositiveIntegerField(default=1)),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcast.podcast')),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-publish_date'],
            },
        ),
    ]
