# Generated by Django 5.0.9 on 2026-07-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_sprint32_add_partner_fk'),
        ('podcast', '0002_podcast_author_podcast_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki podcast ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='platform.partner'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki episode ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_episodes', to='platform.partner'),
        ),
    ]
