# Generated by Django 5.0.9 on 2026-07-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
        ('platform', '0003_sprint32_add_partner_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki folder ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='platform.partner'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki file ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='platform.partner'),
        ),
    ]
