# Generated by Django 5.0.14 on 2026-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_sprint32_add_partner_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='audio_album',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Album (Tag)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='audio_artist',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Artist (Tag)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='audio_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Judul (Tag)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitrate (kbps)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Durasi (detik)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='pipeline_error',
            field=models.TextField(blank=True, default='', verbose_name='Error Pipeline'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='pipeline_status',
            field=models.CharField(choices=[('UPLOADING', 'Sedang Upload'), ('PROCESSING', 'Diproses'), ('READY', 'Siap'), ('FAILED', 'Gagal'), ('ARCHIVED', 'Diarsipkan')], default='READY', max_length=20, verbose_name='Status Pipeline'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Diproses Pada'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='storage_backend',
            field=models.CharField(default='local', max_length=50, verbose_name='Storage Backend'),
        ),
    ]
