# Generated by Django 5.0.9 on 2026-07-15 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('excerpt', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='news/articles/')),
                ('author_name', models.CharField(default='Redaksi', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
