# Generated by Django 5.0.9 on 2026-07-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_allow_comments_article_author_and_more'),
        ('platform', '0003_sprint32_add_partner_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki artikel ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='platform.partner'),
        ),
        migrations.AddField(
            model_name='category',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki kategori ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_categories', to='platform.partner'),
        ),
        migrations.AddField(
            model_name='tag',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki tag ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='platform.partner'),
        ),
    ]
