# Generated by Django 5.0.9 on 2026-07-15 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('highlight_type', models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURED', 'Unggulan'), ('TRENDING', 'Trending'), ('LATEST', 'Terbaru'), ('EDITORS_PICK', 'Pilihan Editor')], max_length=20)),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Artikel'), ('PODCAST', 'Podcast'), ('PODCAST_EPISODE', 'Episode Podcast'), ('PROGRAM', 'Program'), ('EPISODE', 'Episode Siaran')], max_length=25)),
                ('content_id', models.UUIDField()),
                ('title_override', models.CharField(blank=True, default='', max_length=300)),
                ('description_override', models.TextField(blank=True, default='')),
                ('image_override', models.ImageField(blank=True, upload_to='content/highlights/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content Highlight',
                'verbose_name_plural': 'Content Highlights',
                'ordering': ['highlight_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('color', models.CharField(default='#6B4226', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Content Tag',
                'verbose_name_plural': 'Content Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, upload_to='content/authors/avatars/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Artikel'), ('PODCAST', 'Podcast'), ('PODCAST_EPISODE', 'Episode Podcast'), ('PROGRAM', 'Program'), ('EPISODE', 'Episode Siaran'), ('ANNOUNCEMENT', 'Pengumuman')], max_length=25)),
                ('content_id', models.UUIDField()),
                ('scheduled_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publishing Queue',
                'verbose_name_plural': 'Publishing Queue',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Artikel'), ('PODCAST', 'Podcast'), ('PROGRAM', 'Program'), ('EPISODE', 'Episode'), ('BROADCAST', 'Siaran')], max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='#6B4226', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'Content Category',
                'verbose_name_plural': 'Content Categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('name', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Artikel'), ('PODCAST', 'Podcast'), ('PODCAST_EPISODE', 'Episode Podcast'), ('PROGRAM', 'Program'), ('EPISODE', 'Episode Siaran'), ('ANNOUNCEMENT', 'Pengumuman'), ('DISCUSSION', 'Diskusi')], max_length=25)),
                ('content_id', models.UUIDField()),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, default='', max_length=500)),
                ('is_current', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
                'ordering': ['-version_number'],
                'unique_together': {('content_type', 'content_id', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('object_id', models.UUIDField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('og_title', models.CharField(blank=True, default='', max_length=200)),
                ('og_description', models.TextField(blank=True, default='', max_length=500)),
                ('og_image', models.ImageField(blank=True, upload_to='content/seo/og/')),
                ('og_type', models.CharField(default='article', max_length=50)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=20)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_description', models.TextField(blank=True, default='', max_length=500)),
                ('twitter_image', models.ImageField(blank=True, upload_to='content/seo/twitter/')),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('robots', models.CharField(default='index,follow', max_length=30)),
                ('schema_markup', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
