# Generated by Django 5.0.9 on 2026-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='accent_color',
            field=models.CharField(default='#8B5E3C', help_text='Warna aksen partner (hex).', max_length=7),
        ),
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Nama perusahaan/organisasi partner.', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Waktu soft delete.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='smtp_provider',
            field=models.CharField(blank=True, default='', help_text='Default email/SMTP provider slug.', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='storage_provider',
            field=models.CharField(blank=True, default='', help_text='Default storage provider slug.', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='streaming_provider',
            field=models.CharField(blank=True, default='', help_text='Default streaming provider slug.', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='api_key',
            field=models.CharField(default='fdd9825792a6bf49d27fb972b560212274524eb3038b28c910a42971fb478cd5', help_text='API key untuk autentikasi external.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerinvitation',
            name='token',
            field=models.CharField(default='3ca471654ea94a4a5ee031df8bcee10ed97c9d70e5f0767ce74fc462a6abb98d', max_length=64, unique=True),
        ),
    ]
