# Generated by Django 5.0.9 on 2026-07-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_sprint32_partner_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='api_key',
            field=models.CharField(default='392a704f1f586420580b40773fd19f7a6fb47f55c0b57e4e4b2c6d44d26ebc4b', help_text='API key untuk autentikasi external.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerinvitation',
            name='token',
            field=models.CharField(default='e758864b5b775f04835a5acafbe94b1547de903e6f363aae2de90372b08dcc01', max_length=64, unique=True),
        ),
    ]
