# Generated by Django 5.0.14 on 2026-07-15 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('username', models.CharField(help_text='Wajib diisi. Maksimal 150 karakter. Huruf, angka, dan @/./+/-/_ saja.', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Alamat email aktif untuk komunikasi dan reset password.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Nama depan user.', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Nama belakang user.', max_length=150)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Super User'), ('ADMINISTRATOR', 'Administrator'), ('EDITOR', 'Editor/Penulis'), ('VIEWER', 'Viewer/Pembaca')], default='VIEWER', help_text='Klasifikasi peran (RBAC) user di dalam sistem.', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Menentukan apakah user ini aktif. Hapus centang daripada menghapus akun.')),
                ('is_staff', models.BooleanField(default=False, help_text='Menentukan apakah user dapat masuk ke situs admin Django.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Daftar User',
                'ordering': ['-created_at'],
            },
        ),
    ]
