# Generated by Django 5.0.9 on 2026-07-15 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='Akun dikunci sementara sampai waktu ini (dari axes).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Tidak Aktif'), ('SUSPENDED', 'Ditangguhkan'), ('LOCKED', 'Dikunci')], default='ACTIVE', help_text='Status operasional akun user.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Menentukan apakah email user telah diverifikasi.'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah percobaan login gagal berturut-turut.'),
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Jika aktif, user dipaksa mengganti password saat login berikutnya.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Timestamp terakhir user berinteraksi dengan sistem.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Menentukan apakah autentikasi dua faktor aktif untuk akun ini.'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Gagal'), ('PASSWORD_CHANGE', 'Ubah Password'), ('PASSWORD_RESET', 'Reset Password'), ('PROFILE_UPDATE', 'Ubah Profil'), ('ROLE_ASSIGN', 'Tugaskan Peran'), ('PERMISSION_ASSIGN', 'Tugaskan Izin'), ('USER_CREATE', 'Buat User'), ('USER_ACTIVATE', 'Aktifkan User'), ('USER_DEACTIVATE', 'Nonaktifkan User'), ('USER_SUSPEND', 'Tangguhkan User'), ('ACCOUNT_LOCK', 'Kunci Akun'), ('ACCOUNT_UNLOCK', 'Buka Kunci Akun'), ('EMAIL_VERIFY', 'Verifikasi Email'), ('TWO_FACTOR_ENABLE', 'Aktifkan 2FA'), ('TWO_FACTOR_DISABLE', 'Nonaktifkan 2FA')], help_text='Jenis aksi yang dilakukan.', max_length=30)),
                ('resource', models.CharField(blank=True, help_text='Resource atau objek yang terpengaruh.', max_length=200)),
                ('details', models.TextField(blank=True, help_text='Detail tambahan mengenai aksi.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Alamat IP saat aksi dilakukan.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Waktu terjadinya aksi.')),
                ('user', models.ForeignKey(help_text='User yang melakukan aksi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token unik untuk verifikasi email.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu token dibuat.')),
                ('expires_at', models.DateTimeField(help_text='Waktu kadaluarsa token.')),
                ('verified', models.BooleanField(default=False, help_text='Menentukan apakah token sudah digunakan untuk verifikasi.')),
                ('user', models.ForeignKey(help_text='User yang melakukan verifikasi email.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifikasi Email',
                'verbose_name_plural': 'Verifikasi Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('username_attempted', models.CharField(help_text='Username yang dicoba saat login.', max_length=150)),
                ('ip_address', models.GenericIPAddressField(help_text='Alamat IP dari percobaan login.')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent browser dari percobaan login.', max_length=500)),
                ('status', models.CharField(choices=[('SUCCESS', 'Berhasil'), ('FAILED', 'Gagal')], help_text='Status percobaan login.', max_length=10)),
                ('failure_reason', models.CharField(blank=True, help_text='Alasan kegagalan login jika ada.', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Waktu terjadinya percobaan login.')),
                ('user', models.ForeignKey(help_text='User yang melakukan percobaan login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Login',
                'verbose_name_plural': 'Riwayat Login',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Hash password yang pernah digunakan.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu password ini digunakan.')),
                ('user', models.ForeignKey(help_text='User yang memiliki riwayat password ini.', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Password',
                'verbose_name_plural': 'Riwayat Password',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('name', models.CharField(help_text='Nama device atau aplikasi autentikator.', max_length=100)),
                ('secret', models.CharField(help_text='Secret key TOTP yang dienkripsi.', max_length=64)),
                ('is_primary', models.BooleanField(default=True, help_text='Menentukan apakah ini device 2FA utama.')),
                ('user', models.ForeignKey(help_text='User yang memiliki device 2FA ini.', on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device 2FA',
                'verbose_name_plural': 'Device 2FA',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('avatar', models.ImageField(blank=True, help_text='Foto profil user (format: JPG, PNG, max 5MB).', upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Deskripsi singkat tentang diri user.', max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Nomor telepon aktif.', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Tanggal lahir user.', null=True)),
                ('address', models.TextField(blank=True, help_text='Alamat domisili user.', max_length=500)),
                ('user', models.OneToOneField(help_text='User terkait dengan profil ini.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil User',
            },
        ),
    ]
