# Generated by Django 5.0.9 on 2026-07-15 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('station_name', models.CharField(max_length=200)),
                ('station_description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='radio/station/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='radio/station/')),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('country', models.CharField(blank=True, default='Indonesia', max_length=100)),
                ('language', models.CharField(default='id', max_length=10)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('default_volume', models.PositiveIntegerField(default=80, help_text='Volume default player (0-100).')),
                ('autoplay', models.BooleanField(default=False)),
                ('sticky_player', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Radio Station',
                'verbose_name_plural': 'Radio Stations',
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='RadioProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('RADIOBOSS', 'RadioBoss Advance'), ('ICECAST', 'Icecast'), ('SHOUTCAST', 'Shoutcast'), ('AZURACAST', 'AzuraCast')], default='ICECAST', max_length=20)),
                ('api_url', models.URLField(blank=True, default='', max_length=500)),
                ('stream_url', models.URLField(max_length=500)),
                ('backup_stream_url', models.URLField(blank=True, default='', max_length=500)),
                ('metadata_url', models.URLField(blank=True, default='', max_length=500)),
                ('listener_url', models.URLField(blank=True, default='', max_length=500)),
                ('healthcheck_url', models.URLField(blank=True, default='', max_length=500)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Request timeout in seconds.')),
                ('active', models.BooleanField(default=True)),
                ('metadata_format', models.CharField(choices=[('JSON', 'JSON API'), ('XML', 'XML API'), ('ICY', 'ICY Metadata'), ('HTTP', 'HTTP Metadata')], default='JSON', max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Radio Provider',
                'verbose_name_plural': 'Radio Providers',
                'ordering': ['provider_name'],
            },
        ),
        migrations.CreateModel(
            name='NowPlayingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('song_title', models.CharField(blank=True, default='', max_length=500)),
                ('artist', models.CharField(blank=True, default='', max_length=500)),
                ('album', models.CharField(blank=True, default='', max_length=500)),
                ('artwork', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds.')),
                ('elapsed', models.PositiveIntegerField(default=0, help_text='Elapsed time in seconds.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('stream_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('AUTO_DJ', 'Auto DJ'), ('LIVE_DJ', 'Live DJ'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing', to='radio.radioprovider')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='now_playing', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Now Playing Cache',
                'verbose_name_plural': 'Now Playing Cache',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('program', models.CharField(blank=True, default='', max_length=200)),
                ('host', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('listener_peak', models.PositiveIntegerField(default=0)),
                ('average_listeners', models.PositiveIntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListenerStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('current_listeners', models.PositiveIntegerField(default=0)),
                ('peak_listeners', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_stats', to='radio.radioprovider')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_stats', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Listener Statistic',
                'verbose_name_plural': 'Listener Statistics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('response_time', models.FloatField(default=0, help_text='Response time in milliseconds.')),
                ('http_status', models.PositiveIntegerField(default=0)),
                ('provider_status', models.CharField(choices=[('HEALTHY', 'Sehat'), ('DEGRADED', 'Menurun'), ('DOWN', 'Mati'), ('TIMEOUT', 'Timeout')], default='DOWN', max_length=20)),
                ('stream_bitrate', models.PositiveIntegerField(default=0, help_text='Bitrate in kbps.')),
                ('stream_format', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='radio.radioprovider')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Stream Health',
                'verbose_name_plural': 'Stream Health Checks',
                'ordering': ['-last_checked'],
            },
        ),
    ]
