# Generated by Django 5.0.9 on 2026-07-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_sprint32_add_partner_fk'),
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki stasiun radio ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_stations', to='platform.partner'),
        ),
    ]
