# Generated by Django 5.0.9 on 2026-07-15 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcast/announcement/')),
                ('publish_start', models.DateTimeField()),
                ('publish_end', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-publish_start'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Terjadwal'), ('LIVE', 'Sedang Tayang'), ('FINISHED', 'Selesai'), ('CANCELLED', 'Dibatalkan'), ('DELAYED', 'Ditunda')], default='SCHEDULED', max_length=20)),
            ],
            options={
                'verbose_name': 'Broadcast Session',
                'verbose_name_plural': 'Broadcast Sessions',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GuestStar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('full_name', models.CharField(max_length=200)),
                ('biography', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='broadcast/guest/photo/')),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Guest Star',
                'verbose_name_plural': 'Guest Stars',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('full_name', models.CharField(max_length=200)),
                ('stage_name', models.CharField(blank=True, default='', max_length=200)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('biography', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='broadcast/host/avatar/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('instagram', models.CharField(blank=True, default='', max_length=200)),
                ('youtube', models.CharField(blank=True, default='', max_length=200)),
                ('spotify', models.CharField(blank=True, default='', max_length=200)),
                ('facebook', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(blank=True, default='', max_length=200)),
                ('album', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='broadcast.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('full_description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='broadcast/program/thumbnail/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='broadcast/program/banner/')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(default='id', max_length=10)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('target_audience', models.CharField(blank=True, default='', max_length=100)),
                ('content_rating', models.CharField(choices=[('G', 'Umum'), ('PG', 'Parental Guidance'), ('T', 'Remaja'), ('M', 'Dewasa')], default='G', max_length=5)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_programs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_programs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='broadcast.program'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('episode_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='broadcast/episode/cover/')),
                ('recording_audio', models.FileField(blank=True, null=True, upload_to='broadcast/episode/audio/')),
                ('recording_video', models.FileField(blank=True, null=True, upload_to='broadcast/episode/video/')),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('broadcast_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='broadcast.broadcastsession')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='broadcast.program')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='broadcast.program'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('day_of_week', models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu'), ('SUN', 'Minggu')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                ('repeat_weekly', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='broadcast.program')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='broadcast.schedule'),
        ),
        migrations.CreateModel(
            name='EpisodeGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_guests', to='broadcast.episode')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_guests', to='broadcast.gueststar')),
            ],
            options={
                'verbose_name': 'Episode Guest',
                'verbose_name_plural': 'Episode Guests',
                'unique_together': {('episode', 'guest')},
            },
        ),
        migrations.CreateModel(
            name='HostMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUIDv4) primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the object was last updated.')),
                ('is_lead', models.BooleanField(default=False)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_members', to='broadcast.host')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_members', to='broadcast.program')),
            ],
            options={
                'verbose_name': 'Host Member',
                'verbose_name_plural': 'Host Members',
                'unique_together': {('host', 'program')},
            },
        ),
    ]
