# Generated by Django 5.0.9 on 2026-07-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_program_slug'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='episode',
            name='content_format',
            field=models.CharField(choices=[('RICH_TEXT', 'Rich Text'), ('MARKDOWN', 'Markdown'), ('HTML', 'HTML')], default='RICH_TEXT', max_length=15),
        ),
        migrations.AddField(
            model_name='episode',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='og_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='episode',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='broadcast/episode/og/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='episode',
            name='robots',
            field=models.CharField(default='index,follow', max_length=30),
        ),
        migrations.AddField(
            model_name='episode',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Menunggu Review'), ('APPROVED', 'Disetujui'), ('SCHEDULED', 'Terjadwal'), ('PUBLISHED', 'Diterbitkan'), ('ARCHIVED', 'Diarsipkan'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', max_length=20),
        ),
        migrations.AddField(
            model_name='episode',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_author', to='content.author'),
        ),
        migrations.AddField(
            model_name='program',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='program',
            name='content_format',
            field=models.CharField(choices=[('RICH_TEXT', 'Rich Text'), ('MARKDOWN', 'Markdown'), ('HTML', 'HTML')], default='RICH_TEXT', max_length=15),
        ),
        migrations.AddField(
            model_name='program',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='og_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='program',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='broadcast/program/og/'),
        ),
        migrations.AddField(
            model_name='program',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Rendah'), ('NORMAL', 'Normal'), ('HIGH', 'Tinggi'), ('URGENT', 'Mendesak')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='robots',
            field=models.CharField(default='index,follow', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='schema_markup',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Menunggu Review'), ('APPROVED', 'Disetujui'), ('SCHEDULED', 'Terjadwal'), ('PUBLISHED', 'Diterbitkan'), ('ARCHIVED', 'Diarsipkan'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='tags_content',
            field=models.ManyToManyField(blank=True, related_name='programs_content', to='content.contenttag'),
        ),
        migrations.AddField(
            model_name='program',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
