# Generated by Django 5.0.9 on 2026-07-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_episode_canonical_url_episode_content_format_and_more'),
        ('platform', '0003_sprint32_add_partner_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki episode ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_episodes', to='platform.partner'),
        ),
        migrations.AddField(
            model_name='program',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner yang memiliki program ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_programs', to='platform.partner'),
        ),
    ]
